project:
  type: website
  output-dir: docs

website:
  title: "qtm350-quiz02"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: "Life Expectancy vs GDP"
      - href: life-population.qmd
        text: "Life Expectancy and Population"
      - href: country.qmd
        text: "Analysis of a Specific Country Over Time (Thailand)"

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



